### ISSUE TITLE
Missing dependencies when generating services

### ISSUE THREAD

**Issue by phyrog** [ros/genlisp#9] opened 2015-03-10 14:42 UTC
There seems to be a bug related to the asd-file generation. When you generate multiple services that depend on different message-packages, only the dependencies of the last compiled service is added to the asd-file.

You can see this bug in action in this repository: https://github.com/phyrog/genlisp_bug
Just catkin_make it and inspect the generated asd-file. "geometry_msgs" and "std_msgs" should both be listed as dependencies, but only one is listed, depending on which service was generated last.

**Comment by airballking** [comment] 2015-03-11 07:43
@phyrog Thanks for providing this issue. I'll try to confirm this, in the afternoon.

**Comment by airballking** [comment] 2015-03-11 12:19
I can confirm this issue. On a fresh system (ROS Indigo, Ubuntu 14.04, installed and updated this morning), I only see one of the dependencies.

**Comment by airballking** [comment] 2015-03-11 12:36
The bug is limited to generating service files, only. The asd-files of similar message definitions in the same package work out fine. @phyrog I provided a pull request to your sample repo with such message defs.

**Comment by airballking** [comment] 2015-03-11 18:30
I think I have identified the issue. Basically, the `MsgContext` is not filled with the proper data when generating services. The exact issue is here:
https://github.com/ros/genlisp/blob/groovy-devel/src/genlisp/generate.py#L832

`load_srv_from_file` is repeatedly called with the same argument for `file`, i.e. the file of the service definition for which currently build a service, even though that argument should iterate over all service definitions of this package.

Example for the package which @phyrog provided:
We are trying to generate `genlisp_bug/Service1`. `load_srv_from_file` is called two times with the following arguments:
- `load_srv_from_file(msg_context, '/home/georg/ros/indigo/bugs_catkin_ws/src/genlisp_bug/srv/Service2.srv', 'genlisp_bug/Service1')`
- `load_srv_from_file(msg_context, '/home/georg/ros/indigo/bugs_catkin_ws/src/genlisp_bug/srv/Service2.srv', 'genlisp_bug/Service2')`

Instead of: 
- `load_srv_from_file(msg_context, '/home/georg/ros/indigo/bugs_catkin_ws/src/genlisp_bug/srv/Service1.srv', 'genlisp_bug/Service1')`
- `load_srv_from_file(msg_context, '/home/georg/ros/indigo/bugs_catkin_ws/src/genlisp_bug/srv/Service2.srv', 'genlisp_bug/Service2')`

I'm working on a fix. Let's see how it turns out...

**Comment by airballking** [comment] 2015-03-11 18:47
I have pushed a fix to my own fork of `genlisp` into the branch `srv-generation-bug`.

https://github.com/airballking/genlisp/tree/srv-generation-bug

@phyrog Could you please try it out, and verify that it fixes your bug?

**Comment by phyrog** [comment] 2015-03-11 19:37
Yep, I can confirm that your patch fixes the problem. Thanks @airballking

**Comment by airballking** [comment] 2015-03-11 21:42
Just realized: The current fix assume that all services defintion files in our current package are in the same sub-directory. If that is not the case, there should be an error...

@dirk-thomas The top-level functions of genlisp `generate_srv` and `generate_msg` receive as last argument `search-path`. That seems to be a dictionary associating package names with directories to search. In our examples the directories are always the msg-sub-directories of the dependencies, e.g. `{{"std_msgs" : "/opt/ros/indigo/share/std_msgs/cmake/../msg"}}`. Is this the correct behavior? I ask because I passed this search-path to genmsg's `load_srv_from_type` which brakes with such search-path as it cannot find the service definitions:
https://github.com/ros/genmsg/blob/indigo-devel/src/genmsg/msg_loader.py#L126

**Comment by dirk-thomas** [comment] 2015-03-11 22:22
All `msg` and `srv` files are being installed into these locations (never anywhere else):
- /opt/ros/ROSDISTRO/share/PKGNAME/msg
- /opt/ros/ROSDISTRO/share/PKGNAME/srv

**Comment by airballking** [comment] 2015-03-12 08:12
@dirk-thomas Thanks for the clarification! If the build-system enforces these locations then my fix is fine. I'll ask people in my lab to serve as alpha-users before we release.

**Closed as completed** 2015-03-25 18:57 UTC
